/*
    Basic watchlist concept

    1. List header contains user generated or autogenerated list cover based on item count in list
    2. List offers a few different views grid / list
    3. User can add custom description

*/


'use client'
import { TMDBMovieDetails } from "@/server/tmdb/interface"
import { useEffect , useState } from "react"
import { posterImage } from "@/util/helper"
import PosterView from "./PosterView"


export default function List() {
    const [list,  setList] = useState<TMDBMovieDetails[]>([])

    useEffect(() => {
        const list: string | null = localStorage.getItem("watchlist")
        if(!list) return
        const foundList = JSON.parse(list)
        setList(foundList)
    }, [])
        
    return (
        <>
    <div className="w-full flex">
        {list.length < 4 ? <div className="w-[225px] h-[225px] bg-foreground"/> : // shows placeholder cover if length of list is under 4 items 
                <div className="w-[225px] h-[225px] flex-col  bg-foreground">
                <div className="w-full flex">
                <div className="w-[112px] h-[112px] relative overflow-hidden bg-center bg-no-repeat bg-cover"    style={{
                              backgroundImage: `url(${posterImage(list[0].poster_path)})`
                          }}/>
                   <div className="w-[112px] h-[112px] relative overflow-hidden bg-center bg-no-repeat bg-cover"    style={{
                              backgroundImage: `url(${posterImage(list[1].poster_path)})`
                          }}/>
                </div>
                <div className="w-full flex">
                <div className="w-[112px] h-[112px] relative overflow-hidden bg-center bg-no-repeat bg-cover"    style={{
                              backgroundImage: `url(${posterImage(list[2].poster_path)})`
                          }}/>
                   <div className="w-[112px] h-[112px] relative overflow-hidden bg-center bg-no-repeat bg-cover"    style={{
                              backgroundImage: `url(${posterImage(list[3].poster_path)})`
                          }}/>
                </div>
            </div> }


        <div className="flex-col pl-10 pt-3 text-white">
           <div className="pb-5 text-sm tracking-wider font-extralight">
           <span>Public</span>
           </div>
           <h2 className="tracking-wider pb-7 text-3xl font-medium ">Watchlist</h2>
           <p className=" tracking-wider text-sm font-extralight leading-normal w-5/6">Tell us all the things we don’t care to hear about
           how these movies made you feel.</p>
        </div>
     </div>
        <div className="w-full py-20">
            {list.length < 0 ? <div></div> : <PosterView list={list} /> }
        </div>
    </> 
    )
}