import type { Metadata } from 'next'
import { Inter, Manrope, Playfair_Display, Poppins } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar/Sidebar'
import { ClerkProvider } from '@clerk/nextjs'

const poppins = Poppins({subsets: ['latin'] , weight: ["300" , "400" , "500" , "700"] , variable: "--font-poppins"} )
const playfair  = Playfair_Display({subsets: ['latin'] , weight: ["600" , "700"] , variable: "--font-playfair"})

export const metadata: Metadata = {
  title: 'Bxoffice',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Sidebar/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}
